Add a direct access to tables, for stronger typing.
josephbestjames/airtable.py pull request #33
Opened 2020-09-11 11:52 UTC by zozoens31

2020-11-13 08:47 UTC, pcorpet requested changes
Thanks for the suggestion, I do like this new API.

2020-11-13 08:47 UTC, pcorpet commented on airtable/airtable.py
> +    def __getattr__(self, name):
Please add some tests.

2020-11-13 08:47 UTC, pcorpet commented on airtable/airtable.py
> +class AirtableTable(object):
Please rename this simply `Table`

2021-01-20 08:14 UTC, zozoens31 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/josephbestjames/airtable.py/33#-:-MRTqvj5C3qzzPoNKaUf:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-20 08:37 UTC, pcorpet reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/josephbestjames/airtable.py/33#-:-MRTwICB10hHkkxb3dj5:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-20 08:37 UTC, pcorpet approved these changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/josephbestjames/airtable.py/33)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zozoens31)



<!-- Sent from Reviewable.io -->

2021-01-20 08:53 UTC, merged