Remove unnecessary import alias
josephbestjames/airtable.py pull request #43
Opened 2021-01-27 09:46 UTC by withshubh

### Description
Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/airtable.py/issues/). This PR fixes a few of them.

### Summary of fixes
- Removed unnecessary import alias

2021-02-07 07:48 UTC, withshubh commented
Hi @josephbestjames :wave: 

Please have a look at this PR! :sparkles:

2021-02-10 08:28 UTC, pcorpet commented
This file (__init__.py) is going away soon.

2021-02-10 16:28 UTC, withshubh commented
> This file (**init**.py) is going away soon.

Hey @pcorpet 

Fixed three more issues. :sparkles:

2021-02-18 09:39 UTC, withshubh commented
Hey @josephbestjames :wave: 

Please have a look at this PR!

2021-04-02 17:34 UTC, withshubh commented
@josephbestjames @pcorpet :wave: 
review this PR, please!

2021-04-02 20:27 UTC, pcorpet requested changes

2021-04-02 20:27 UTC, pcorpet commented on airtable/__init__.py
> +    Airtable,
Please rebase

2021-04-02 20:27 UTC, pcorpet commented on airtable/airtable.py
> +class Airtable():
We still support python2, so we're not ready to drop this

2021-04-02 20:27 UTC, pcorpet commented on airtable/airtable.py
> +        raise AirtableError(
Please rebase, I think this change got in in another commit

2021-04-03 06:16 UTC, withshubh commented
Hi @pcorpet Done! :sparkles: 

Also, please consider having a look at these [issues](https://deepsource.io/gh/withshubh/airtable.py/issues/?category=recommended).

2021-04-03 11:52 UTC, pcorpet commented
This PR now hasn't any interesting changes to add.

2021-04-03 11:52 UTC, closed without merging